### ISSUE TITLE
Registering?

### ISSUE THREAD

**Issue by krcools** [koehlerson/gmsh.jl#1]
Thank you for this package. Would you consider registering it, so that it can appear as an indirect dependency in other projects?

**Comment by koehlerson** [comment]
Initially, all of this should be in [Gmsh.jl](https://github.com/JuliaFEM/Gmsh.jl), which happens to be registered. This is why I can't register this package, see https://github.com/JuliaRegistries/General/pull/27173#event-4161377744 

I would like to revive Gmsh.jl but I need a documenter deploy key, which I requested here https://github.com/JuliaFEM/Gmsh.jl/issues/11

So this package will never be registered. Maybe I can merge it at some point in Gmsh.jl

**Comment by krcools** [comment]
That's a shame because your package works under Windows whereas Gmsh.jl does not. There is also GmshTools.jl, which requires manual installation of the binary artefact.

**Comment by koehlerson** [comment]
Let's see if I can merge it soon in Gmsh.jl

**Comment by krcools** [comment]
Actually, 22 hours ago a new GmshTools version was released that does not require separate installation of the binary, but relies on gmsh_jll instead. Fast-moving world!
